const { model, Schema } = require("mongoose");
const paginator = require("mongoose-paginate-v2");

const listingAndReviewSchema = new Schema({
  _id: String,
  listing_url: String,
  summary: String,
  space: String,
  description: String,
  neighborhood_overview: String,
  transit: String,
  house_rules: String,
  property_type: String,
  room_type: String,
  bed_type: String,
  minimum_nights: String,
  maximum_nights: String,
  cancellation_policy: String,
  number_of_reviews: Number,
  bathrooms: Number,
  amenities: [String],
  price: Number,
  guests_included: Number,
  images: {
    thumbnail_url: String,
    medium_url: String,
    picture_url: String,
    xl_picture_url: String,
  },
  host: {
    host_id: String,
    host_url: String,
    host_name: String,
    host_location: String,
    host_about: String,
    host_response_time: String,
    host_thumbnail_url: String,
    host_picture_url: String,
    host_response_rate: Number,
    host_is_superhost: Boolean,
    host_has_profile_pic: Boolean,
    host_identity_verified: Boolean,
    host_listings_count: Number,
    host_total_listings_count: Number,
    host_verifications: [String],
  },
  address: {
    street: String,
    suburb: String,
    government_area: String,
    market: String,
    country: String,
    country_code: String,
    location: {
      type: String,
      is_location_exact: Boolean,
      coordinates: [String],
    },
  },
  review_scores: {
    review_scores_accuracy: Number,
    review_scores_cleanliness: Number,
    review_scores_checkin: Number,
    review_scores_communication: Number,
    review_scores_location: Number,
    review_scores_value: Number,
    review_scores_rating: Number,
  },
  reviews: [
    {
      _id: String,
      date: Date,
      String,
      listing_id: String,
      reviewer_id: String,
      reviewer_name: String,
      comments: String,
    },
  ],
  accommodates: Number,
  bedrooms: Number,
  beds: Number,
});

listingAndReviewSchema.plugin(paginator);
module.exports = model(
  "ListingAndReviews",
  listingAndReviewSchema,
  "listingsAndReviews"
);
